name: actions-test
on: [push]
env:
  VAR_NAME: "Global value"
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Oppstartsmelding"
        run: "Hello"
      - name: "Test global var as $VAR_NAME"
        run: echo "Test value $VAR_NAME"